version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "taskbox"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3xixg3eodpa9"
s3_prefix = "taskbox"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppId=\"taskbox\" Password=\"authpass\""
image_repositories = []
