AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Task Dashboard for yourself.

Transform: AWS::Serverless-2016-10-31

Parameters:
  AppId:
    Type: String
  Password:
    Type: String

Globals:
  Function:
    Timeout: 10
    Layers:
      - !Ref Taskboxlayer

Resources:
  taskbox:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: taskbox
      CodeUri: ./taskbox
      Handler: taskbox.index.lambda_handler
      Runtime: python3.9
      MemorySize: 180
      Description: A crontask frame and HTTP service.
      Environment:
        Variables:
          DDB_TABLE: !Ref taskboxddbtable
          # 用来登录web的强密码
          auth_passwd: !Sub '${Password}'
          FUNC_ARN: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mytaskbox'
      # 如果日志出现缺少dynamodb get权限，在函数配置界面创个不用鉴权的函数url再试试
      Policies:
        - AWSLambda_FullAccess
        - AmazonDynamoDBFullAccess
        - AmazonEventBridgeSchedulerFullAccess
        - AmazonEventBridgeFullAccess
      Events:
        ExplicitApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref http
            Path: /auth/login
            Method: POST

  http:
    Type: AWS::Serverless::HttpApi
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      DefaultRouteSettings:
        ThrottlingBurstLimit: 50
      FailOnWarnings: true
      RouteSettings:
        "POST /auth/login":
          ThrottlingBurstLimit: 1 # overridden in HttpApi Event

  Taskboxlayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Taskboxlayer
      Description: "flask rsa requests"
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete

  # libs:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     LayerName: taskboxlayer
  #     Description: jinja2 + rsa + requests + boto3 1.26
  #     Content:
  #       S3Bucket: !Sub 'aws-${AWS::Region}-${AWS::AccountId}-${AppId}-pipe'
  #       S3Key: layer/taskboxlayer.zip

  AccessLogs:
    Type: AWS::Logs::LogGroup

  taskboxddbtable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
        -
          AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "name"
          KeyType: "RANGE"

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${http}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: http
