on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - run: find ./ -name requirements.txt -type f -exec pip install -t python/ -r "{}" \;
      - run: zip taskboxlayer.zip -q -r python/
      - run: aws lambda publish-layer-version --layer-name taskboxlayer --zip-file fileb://taskboxlayer.zip  --compatible-runtimes python3.9 --compatible-architectures "arm64" "x86_64" --license-info "MIT"
      - run: rm -rf taskboxlayer.zip python/
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
